"""Add size column to storageunit table

Revision ID: 2ebafec72d23
Revises: b74410a60863
Create Date: 2025-10-29 01:45:19.962545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebafec72d23'
down_revision = 'b74410a60863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storageunit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storageunit', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
